### ISSUE TITLE
Compiler constants don't transer

### ISSUE THREAD

**Issue by BigPhilCombo** [code-orchestra/colt-fd-plugin#11]
When exporting a project from FD to Colt, default FlashDevelop compiler constants - CONFIG::Release and CONFIG::Debug do not get transferred to the COLT project.

**Comment by makc** [comment]
ha, someone does use them ) I could probably put those in "additional options". what's the syntax?

**Comment by BigPhilCombo** [comment]
-define+=CONFIG::debug,true -define+=CONFIG::release,false

Not sure if it would be possible (because of the custom compiling that you
do) but maybe it would be easier to just use the FlashDevelop
configuration.xml files?

On Tue, Jun 18, 2013 at 9:52 AM, makc notifications@github.com wrote:

> ha, someone does use them ) I could probably put those in "additional
> options". what's the syntax?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/code-orchestra/colt-fd-plugin/issues/11#issuecomment-19612363
> .

## 

Phillip Chertok

**Comment by makc** [comment]
you can use those. there's an option in plugin settings.

**Comment by BigPhilCombo** [comment]
OK I get it.   I think it might make sense to have those settings work on a
per-project basis because right now it seems to apply to all projects or am
I mistaken?

On Tue, Jun 18, 2013 at 9:58 AM, makc notifications@github.com wrote:

> you can use those. there's an option in plugin settings.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/code-orchestra/colt-fd-plugin/issues/11#issuecomment-19612718
> .

## 

Phillip Chertok

**Comment by makc** [comment]
Yes, all plugin settings are global in order to use FD settings editor. It is possible to make per-project settings, but then I will have to make UI for that :hourglass:

**Comment by BigPhilCombo** [comment]
Understood.

On Tue, Jun 18, 2013 at 10:07 AM, makc notifications@github.com wrote:

> Yes, all plugin settings are global in order to use FD settings editor. It
> is possible to make per-project settings, but then I will have to make UI
> for that [image: :hourglass:]
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/code-orchestra/colt-fd-plugin/issues/11#issuecomment-19613297
> .

## 

Phillip Chertok

**Comment by makc** [comment]
[Reference](http://www.flashdevelop.org/wikidocs/index.php?title=AS3_Conditional_Compilation):

> FlashDevelop automatically sets 6 constants... AIR... n the Project Properties, Compiler Options tab, you can populate the "Compiler Constants" list. 

This request just got 6 times harder :unamused:

**Comment by BigPhilCombo** [comment]
Don't worry about it.  Since we can load from FD config then it is fine.

On Tue, Jun 18, 2013 at 9:06 PM, makc notifications@github.com wrote:

> Referencehttp://www.flashdevelop.org/wikidocs/index.php?title=AS3_Conditional_Compilation
> :
> 
> FlashDevelop automatically sets 6 constants... AIR... n the Project
> Properties, Compiler Options tab, you can populate the "Compiler Constants"
> list.
> 
> This request just got 6 times harder [image: :unamused:]
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/code-orchestra/colt-fd-plugin/issues/11#issuecomment-19655060
> .

## 

Phillip Chertok

**Comment by makc** [comment]
I will not be able to send these 6 constants without fully recreating [FDBuild logic](https://code.google.com/p/flashdevelop/source/browse/trunk/FD4/External/Tools/FDBuild/Building/AS3/FlexConfigWriter.cs#60):

> [6/19/13 3:11:58 PM] Philippe Elsass: they aren't exposed outside the generated flex config file
