### ISSUE TITLE
[FCSHProcessHandler] The pipe is being closed

### ISSUE THREAD

**Issue by muratyilmaz** [code-orchestra/colt-fd-plugin#2]
Why??? can you help me?

![untitled-2](https://f.cloud.github.com/assets/1283764/506427/5d53e4c0-bd4e-11e2-90d5-dc8d7fa7c3ff.jpg)

**Comment by makc** [comment]
This is not really plugin issue, ~~you probably need to report it at http://codeorchestra.myjetbrains.com/youtrack/issues/CFB with your test project zipped. Unless it happens with all the projects, then we will need your system/installation details~~.

**Comment by makc** [comment]
Wait. I've been told that this is fixed in current COLT build :) Just download it again and re-install.

**Comment by muratyilmaz** [comment]
everything is ok,thanks :)
