### ISSUE TITLE
Unhandled Exception has occurred in your application

### ISSUE THREAD

**Issue by tcorbet** [code-orchestra/colt-fd-plugin#7]
FD Version 4.4.2
Plugin Version - Branch Master, Last Commit May 28
Host OS:  Windows XP

Followed FD instructions for4 intalling 3rd Pary Plugin -- dropped ColtPlugin.dll in OS-appropriate directory.  On restart, Colt Plugin icon appeared as expected.

Clicked on Icon got the exception which provides this detail:

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

*************\* Exception Text **************
System.ComponentModel.Win32Exception: No application is associated with the specified file for this operation
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(String fileName)
   at ColtPlugin.PluginMain.OpenInCOLT()
   at ColtPlugin.PluginMain.OnClick(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

*************\* Loaded Assemblies **************
mscorlib
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.3643 (GDR.050727-3600)
##     CodeBase: file:///C:/WINDOWS/Microsoft.NET/Framework/v2.0.50727/mscorlib.dll

FlashDevelop
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.0.0
##     CodeBase: file:///E:/ShareWare/FlashDev/FlashDevelop.exe

PluginCore
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
##     CodeBase: file:///E:/ShareWare/FlashDev/PluginCore.DLL

System.Windows.Forms
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.3645 (GDR.050727-3600)
##     CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Windows.Forms/2.0.0.0__b77a5c561934e089/System.Windows.Forms.dll

System
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.3644 (GDR.050727-3600)
##     CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll

System.Drawing
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.3644 (GDR.050727-3600)
##     CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Drawing/2.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll

System.Xml
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.3082 (QFE.050727-3000)
##     CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Xml/2.0.0.0__b77a5c561934e089/System.Xml.dll

AirProperties
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
##     CodeBase: file:///E:/ShareWare/FlashDev/Plugins/AirProperties.DLL

AS2Context
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
##     CodeBase: file:///E:/ShareWare/FlashDev/Plugins/AS2Context.DLL

ASCompletion
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
##     CodeBase: file:///E:/ShareWare/FlashDev/Plugins/ASCompletion.DLL

AS3Context
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
##     CodeBase: file:///E:/ShareWare/FlashDev/Plugins/AS3Context.DLL

Aga
    Assembly Version: 1.7.0.0
    Win32 Version: 1.7.0.0
##     CodeBase: file:///E:/ShareWare/FlashDev/Aga.DLL

XMLCompletion
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
##     CodeBase: file:///E:/ShareWare/FlashDev/Plugins/XMLCompletion.DLL

ASClassWizard
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
##     CodeBase: file:///E:/ShareWare/FlashDev/Plugins/ASClassWizard.DLL

BasicCompletion
    Assembly Version: 1.0.0.38101
    Win32 Version: 1.0.0.38101
##     CodeBase: file:///E:/ShareWare/FlashDev/Plugins/BasicCompletion.DLL

BookmarkPanel
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
##     CodeBase: file:///E:/ShareWare/FlashDev/Plugins/BookmarkPanel.DLL

BridgeSettings
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
##     CodeBase: file:///E:/ShareWare/FlashDev/Plugins/BridgeSettings.DLL

CodeAnalyzer
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
##     CodeBase: file:///E:/ShareWare/FlashDev/Plugins/CodeAnalyzer.DLL

CodeFormatter
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
##     CodeBase: file:///E:/ShareWare/FlashDev/Plugins/CodeFormatter.DLL

Antlr3
    Assembly Version: 3.1.3.42154
    Win32 Version: 3.1.3.42154
##     CodeBase: file:///E:/ShareWare/FlashDev/Antlr3.DLL

CodeRefactor
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
##     CodeBase: file:///E:/ShareWare/FlashDev/Plugins/CodeRefactor.DLL

CssCompletion
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
##     CodeBase: file:///E:/ShareWare/FlashDev/Plugins/CssCompletion.DLL

DataEncoder
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
##     CodeBase: file:///E:/ShareWare/FlashDev/Plugins/DataEncoder.DLL

fdb.j4n
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
##     CodeBase: file:///E:/ShareWare/FlashDev/Plugins/fdb.j4n.DLL

jni4net.n-0.8.4.0
    Assembly Version: 0.8.4.0
    Win32 Version: 0.8.4.0
##     CodeBase: file:///E:/ShareWare/FlashDev/Plugins/jni4net.n-0.8.4.0.DLL

FileExplorer
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
##     CodeBase: file:///E:/ShareWare/FlashDev/Plugins/FileExplorer.DLL

FlashConnect
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
##     CodeBase: file:///E:/ShareWare/FlashDev/Plugins/FlashConnect.DLL

System.Configuration
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.3053 (netfxsp.050727-3000)
##     CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Configuration/2.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll

FlashDebugger
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
##     CodeBase: file:///E:/ShareWare/FlashDev/Plugins/FlashDebugger.DLL

FlashLogViewer
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
##     CodeBase: file:///E:/ShareWare/FlashDev/Plugins/FlashLogViewer.DLL

FlashViewer
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
##     CodeBase: file:///E:/ShareWare/FlashDev/Plugins/FlashViewer.DLL

HaXeContext
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
##     CodeBase: file:///E:/ShareWare/FlashDev/Plugins/HaXeContext.DLL

jni4net.n.w32.v20-0.8.4.0
    Assembly Version: 0.8.4.0
    Win32 Version: 0.8.4.0
##     CodeBase: file:///E:/ShareWare/FlashDev/Plugins/jni4net.n.w32.v20-0.8.4.0.DLL

LayoutManager
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
##     CodeBase: file:///E:/ShareWare/FlashDev/Plugins/LayoutManager.DLL

LoomContext
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
##     CodeBase: file:///E:/ShareWare/FlashDev/Plugins/LoomContext.DLL

ProjectManager
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
##     CodeBase: file:///E:/ShareWare/FlashDev/Plugins/ProjectManager.DLL

MacroManager
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
##     CodeBase: file:///E:/ShareWare/FlashDev/Plugins/MacroManager.DLL

OutputPanel
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
##     CodeBase: file:///E:/ShareWare/FlashDev/Plugins/OutputPanel.DLL

PHPContext
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
##     CodeBase: file:///E:/ShareWare/FlashDev/Plugins/PHPContext.DLL

SwfOp
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
##     CodeBase: file:///E:/ShareWare/FlashDev/SwfOp.DLL

System.Runtime.Remoting
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.3053 (netfxsp.050727-3000)
##     CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Runtime.Remoting/2.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll

ResultsPanel
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
##     CodeBase: file:///E:/ShareWare/FlashDev/Plugins/ResultsPanel.DLL

SourceControl
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
##     CodeBase: file:///E:/ShareWare/FlashDev/Plugins/SourceControl.DLL

StartPage
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
##     CodeBase: file:///E:/ShareWare/FlashDev/Plugins/StartPage.DLL

System.Web
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.3634 (GDR.050727-3600)
##     CodeBase: file:///C:/WINDOWS/assembly/GAC_32/System.Web/2.0.0.0__b03f5f7f11d50a3a/System.Web.dll

TaskListPanel
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
##     CodeBase: file:///E:/ShareWare/FlashDev/Plugins/TaskListPanel.DLL

ColtPlugin
    Assembly Version: 1.0.0.23572
    Win32 Version: 1.0.0.23572
##     CodeBase: file:///C:/Documents%20and%20Settings/tcorbet/Local%20Settings/Application%20Data/FlashDevelop/Plugins/ColtPlugin.dll

pkyqnys_
    Assembly Version: 1.0.0.0
    Win32 Version: 2.0.50727.3644 (GDR.050727-3600)
##     CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll

wa5cxolb
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.3644 (GDR.050727-3600)
##     CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll

*************\* JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by makc** [comment]
Is that Terry Corbet? Man, I have not seen your messages in ages.

Any way, this part

> System.ComponentModel.Win32Exception: No application is associated with the specified file for this operation
> at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
> at System.Diagnostics.Process.Start()

seems to say that COLT is not properly installed. What are your system/installation details? Can you open *.colt files by double-clicking them in explorer?

(regardless, I should add try-catch there)

**Comment by tcorbet** [comment]
Yes sir, same, very old geek.

I probably should not have submitted an Issue for your plugin, but since it got all that great publicity the other day, I thought you would start getting hits from a lot of different development environments that you had not seen in the earlier part of May when you evidently did most of the work.  Feel free to just delete it.

To answer your questions:  The Colt install was good, but since I had no prior Colt experience, I am not sure whether my quick test proved that it was working properly.  I just clicked through to create a HelloWorld Actionscript only Main class and made sure that the standalone flash debugger ran it ok.

My interest, since I don't have the assets for developing mobile applications was just to see whether or not I could improve on my turn-around test workflow with an Away3D Extended Desktop AIR application that has a somewhat complex Scenegraph.  Since I have long been a FD user and even when I was working on Sandy, I used fcsh to get rapid testing from the command line with a vi editior, I am pretty productive most of the time with just those tools.  In this case, since I only have heuristics, not solid algorithms for the placement of the objects, I have to run a lot of quick tests to view the result -- 2-4 per minute.  So, if Colt inside FD could increase that to 5-6 minute, it would be helpful, but not mission critical -- not $300 mission-critical.

Colt is no doubt a nice product, but it is way too bloated already.  The resource consumption -- RAM and CPU cycles just starting Colt up while it massages my sources is worrisome, so, for now, I have uninstalled it.

I mostly stumble upon makc a couple of times a year whenever I get into some new Actionscript project.  I am always amazed to pull up some screencast of something that I wish I had witnessed, and there in the dialog will almost always be the infamous makc asking some nasty question while some poor Russian or Frenchman is trying to concentrate on his presentation of the latest/greatest 3D technique.  Your work product/ track record remains very impressive, so when Philippe is shouting your name in praise, I suspect you've done something quite good.

Best regards,

Terry Corbet
  ----- Original Message -----

**Comment by makc** [comment]
> Feel free to just delete it.

It will be closed when I add try-catch there.

> I have to run a lot of quick tests to view the result -- 2-4 per minute. So, if Colt inside FD could increase that to 5-6 minute, it would be helpful, but not mission critical -- not $300 mission-critical.

I don't know how much free time do you have, but if you have time to record ~3 minutes video of COLT in action on your project, you get the license for free. And a chance to win some apple hardware.
